### ISSUE TITLE
Liens de téléchargement

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/pct-wiki#4]
Les liens de téléchargement sur [cette page](https://rssw.eu/pct-wiki/Index/) doivent pointer sur la dernière release : https://github.com/Riverside-Software/pct/releases/latest

**Comment by BastienThoral** [comment]
Les 2 liens pointent dorénavant vers l'URL :
https://github.com/Riverside-Software/pct/releases/latest

Les liens sont décrits dans le fichier de données _data/home_callouts.yml
